% All left features of data with label of 52 subjects
all_left_subj = {subj_1_left_data_with_label subj_2_left_data_with_label ...
    subj_3_left_data_with_label subj_4_left_data_with_label .....
    subj_5_left_data_with_label subj_6_left_data_with_label .....
    subj_7_left_data_with_label subj_8_left_data_with_label .....
    subj_9_left_data_with_label subj_10_left_data_with_label .....
    subj_11_left_data_with_label subj_12_left_data_with_label .....
    subj_13_left_data_with_label subj_14_left_data_with_label .....
    subj_15_left_data_with_label subj_16_left_data_with_label .....
    subj_17_left_data_with_label subj_18_left_data_with_label .....
    subj_19_left_data_with_label subj_20_left_data_with_label .....
    subj_21_left_data_with_label subj_22_left_data_with_label .....
    subj_23_left_data_with_label subj_24_left_data_with_label .....
    subj_25_left_data_with_label subj_26_left_data_with_label .....
    subj_27_left_data_with_label subj_28_left_data_with_label .....
    subj_29_left_data_with_label subj_30_left_data_with_label .....
    subj_31_left_data_with_label subj_32_left_data_with_label .....
    subj_33_left_data_with_label subj_34_left_data_with_label .....
    subj_35_left_data_with_label subj_36_left_data_with_label .....
    subj_37_left_data_with_label subj_38_left_data_with_label .....
    subj_39_left_data_with_label subj_40_left_data_with_label .....
    subj_41_left_data_with_label subj_42_left_data_with_label .....
    subj_43_left_data_with_label subj_44_left_data_with_label .....
    subj_45_left_data_with_label subj_46_left_data_with_label .....
    subj_47_left_data_with_label subj_48_left_data_with_label .....
    subj_49_left_data_with_label subj_50_left_data_with_label .....
    subj_51_left_data_with_label subj_52_left_data_with_label};

% Total time
time = 700;

for index = 1:52
    subj = [1:52];      % Total subjects 52
    subj(index)=[];
    train_data = all_left_subj(subj);    % 51 subjects data as train data
    
    for tata=1:51
        poke = tata-1;
        training_data(time*poke+1:time*tata,:) = train_data{1,tata}(:,1:end);
    end
    
    % actual label
    test_label = feature_label; 
    test_data = all_left_subj(index); 
    test_data = test_data{:}(:,2:end);
    
    % Generate train Model
    train_model= trainClassifier(training_data);
    
    % Predicted label
    predict = train_model.predictFcn(test_data);
    
    % Performace comparison
    % (Accuracy, Sensitivity, Specificity, Precision, Recall, F-Measure, G-mean)
    rating_left(index,:) = Evaluate(test_label,predict);
end

